version: "3"

services:
  # In development, open ES port so host API can connect to it
  elasticsearch:
    build:
      context: ./docker/elasticsearch
    ports:
      - 9200:9200

  data:
    build:
      context: ./packages/code-du-travail-data
      args:
        BASE_IMAGE: cdtn_master:local

  nlp_api:
    build:
      context: ./packages/code-du-travail-nlp
      args:
        BASE_IMAGE: cdtn_master:local
    environment:
      - FLASK_RUN_PORT=$NLP_PORT
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - NLP_URL=http://localhost

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.0
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
